var words = [
  "America junior ",
  "America's crud bucket ",
  "annual gift man ",
  "assal horizontology ",
  "avoision ",
  "badbye ",
  "bagzooka ",
  "bartesque ",
  "basegame ",
  "bathiola ",
  "be-musement park ",
  "beginualize ",
  "beginulate ",
  "betsy bleedingheart ",
  "biz-zay ",
  "blingwad ",
  "blubber-in-law ",
  "blundering numbskullery ",
  "bolognium ",
  "bonus eruptus ",
  "boo-urns ",
  "boostafazoo ",
  "bovine university ",
  "brassafrax ",
  "bumbled-bee ",
  "California cheeseburger ",
  "capdabbler ",
  "car hole ",
  "chazwazers ",
  "cheese-eating surrender monkeys ",
  "chestal ",
  "chester a. arthritis ",
  "chocotastic ",
  "Christmas Ape ",
  "Christmas Ape goes to Summer Camp ",
  "clouseauesque ",
  "commie-nazis ",
  "crantastic ",
  "crap factory ",
  "craptacular ",
  "crayola oblongata ",
  "crisitunity ",
  "cromulent ",
  "d'oh! ",
  "dealie ",
  "debigulator ",
  "deceleratrix ",
  "dickety ",
  "dickety-six miles ",
  "diddily ",
  "diddly ",
  "doctorb ",
  "dodgerock ",
  "dollareydoos ",
  "don'ter ",
  "doobob ",
  "doodily ",
  "dorkus molorkus ",
  "dumbening ",
  "dungeonarium ",
  "eat my shirt ",
  "eat my shorts ",
  "eat our shirts ",
  "eddie punch-clock ",
  "eedily ",
  "electromicide ",
  "embiggen ",
  "esquilax ",
  "fancy store-bought dirt ",
  "fantastipotamus ",
  "fatard ",
  "faxtrola ",
  "fireworks factory ",
  "fishmas ",
  "flanswered ",
  "flunjer ",
  "foodbag ",
  "foodrinkery ",
  "forfty ",
  "foundling-a-ding ",
  "frinkahedron ",
  "fudrucker ",
  "fuhrerific ",
  "gamblor ",
  "gangsta city ",
  "garbagewater ",
  "genius at work ",
  "glavin ",
  "groin-grabbingly ",
  "ha ha! ",
  "hey-dilly-ho ",
  "holy flurking schnit ",
  "homerhol ",
  "homersexual ",
  "iced cream ",
  "impy & chimpy ",
  "inflammable",
  "introubulate ",
  "jebeditis ",
  "jebus ",
  "jiminy jillikers ",
  "johnny come-not-lies ",
  "johnny lunchpail ",
  "jumping box ",
  "juzz ",
  "kapowza ",
  "killbot factory ",
  "knifey spooney ",
  "knifey wifey ",
  "knowitallism ",
  "knowledgeum ",
  "kung-fu hippie ",
  "kwyjibo ",
  "lamarella ",
  "land cow ",
  "land monster ",
  "lard-ho ",
  "learnatorium ",
  "liberty log ",
  "lupper ",
  "magumba ",
  "malparkage ",
  "mazuma ",
  "megacide ",
  "meh ",
  "menapplause ",
  "menu boy ",
  "microcalifragilistics ",
  "milhousing ",
  "mobilomobile ",
  "money fight ",
  "neglecterino ",
  "neighborino ",
  "nervous pervis ",
  "nincompoop ",
  "no-breath ",
  "nuclear whipping boy ",
  "nucleon ",
  "nuisancefon ",
  "nulecule ",
  "okely dokely ",
  "one way passage to the boneyard ",
  "onetuplet ",
  "oodily ",
  "outrageous paradigm ",
  "ovulicious ",
  "paradigm ",
  "paraplegiarino ",
  "pasghetti ",
  "perspicacity ",
  "pointy kitty ",
  "pollutinest ",
  "poochie ",
  "posturologists ",
  "pretzeled bread ",
  "pricetaggery ",
  "proactive ",
  "purple is a fruit ",
  "quetzalzacatenango ",
  "rappin' surfer ",
  "rastafy ",
  "redorkulated ",
  "retirony ",
  "reverse vampires ",
  "reversifying glass ",
  "riding the midnight train to slab city ",
  "rock and/or roll ",
  "sacrilicious ",
  "sally housecoat ",
  "sandal-wearing goldfish tenders ",
  "saxamaphone ",
  "scalpal ",
  "science pole ",
  "scientician ",
  "scotchtoberfest ",
  "senseless dunderpate ",
  "she. u.i. ",
  "shinning ",
  "Shiva H. Vishnu ",
  "skanks for nothing ",
  "skittlebrau ",
  "smarch ",
  "smashy smashy ",
  "smell ya later ",
  "smendler ",
  "smokesperson ",
  "snacktacular ",
  "sophistimacated doowhackey ",
  "speedholes ",
  "spiritual de-pantsing ",
  "spokesrebel ",
  "squozen ",
  "stabby ",
  "steamed hams ",
  "stinkables ",
  "successmanship ",
  "suck shack ",
  "sunblocker ",
  "superliminal ",
  "suspicious aloysius ",
  "swedish lunchbox ",
  "swishifying ",
  "telepanhandling ",
  "texas left ",
  "texas penny ",
  "the congealed group ",
  "the old fork in the eye ",
  "the whipped group ",
  "throughhole ",
  "tomacco ",
  "tomorry ",
  "traumedy ",
  "tromboner ",
  "unblowuppable ",
  "underreacting ",
  "unfaceuptoable ",
  "unpossible ",
  "unpossible ",
  "up and at them ",
  "uppity box ",
  "velocitator ",
  "we were eating rotisserie chicken ",
  "well-wisher ",
  "wiggle puppy ",
  "wizard's key ",
  "woozle wuzzle ",
  "word hole ",
  "Worst Episode Ever. ",
  "yoink ",
  "zazz ",
  "zing ",
  "zork ",
  "zuh "
];

var $container = document.createElement("div");
$container.className = "container";
document.body.appendChild($container);


var $paragraph = document.createElement("p");
$paragraph.className = "paragraph";
$container.append($paragraph);

var $paragraphText = [];
var randomWordNumber;

function loremSimpson() {
    wordNum = document.getElementById("wordNumId").value - 4;

    $paragraphText = ["Lorem Simpson ", "perfectly cromulent "];
    $(".paragraph").empty();
    for (var i = 0; i < wordNum; i++) {

        randomWordNumber = Math.floor((Math.random() * 233) + 1);

        $paragraphText.push(words[randomWordNumber]);

    }

    for (var j = 0; j < $paragraphText.length; j++) {

        $paragraph.append($paragraphText[j]);

    }

};
